apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fabric8-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-service
            port:
              name: http
      - path: /registry
        pathType: Prefix
        backend:
          service:
            name: registry-service
            port:
              name: http