apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: landscaper-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: landscaper-role
subjects:
- kind: ServiceAccount
  name: landscaper-sa
