apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: landscaper-role
rules:
- apiGroups: ["*", "networking.k8s.io"]
  resources: ["deployments","services", "ingresses"]
  verbs: ["get","list","create","delete","patch", "update"]
