apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-role
subjects:
- kind: ServiceAccount
  name: registry-sa
