apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric8-admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: etone/fabric8scape-admin:r1
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
